#!/usr/bin/with-contenv bash

exec \
	s6-setuidgid abc /usr/bin/java \
	-Xmx512M -Xms20M -XX:+UseG1GC -XX:GCTimeRatio=1 \
	-XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 \
	-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true \
	-Dorg.restlet.engine.loggerFacadeClass=org.restlet.ext.slf4j.Slf4jLoggerFacade \
	-Dderby.system.home=/config/serviio/library \
	-Dserviio.home=/app/serviio -Dplugins.location=/config/serviio \
	-Dserviio.defaultTranscodeFolder=/transcode -Dffmpeg.location=/usr/bin/ffmpeg \
	-Ddcraw.location=/usr/bin/dcraw -classpath \
	/app/serviio/lib/*:/config/serviio/config org.serviio.MediaServer
